# This file is a template, and might need editing before it works on your project.
# use the official gcc image, based on debian
# can use verions as well, like gcc:5.2
# see https://hub.docker.com/_/gcc/

test:alltests:
  only:
   - schedules
   - web
   - merge_requests
  stage: build
  tags:
   - raspberrypi
  script:
    - mkdir build
    - cd build
    - cmake -DCMAKE_BUILD_TYPE=Debug ..
    - cmake --build . --target test_all_unit
  stage: test
  tags:
   - raspberrypi
  script:
    - cd build/test
    - sudo ./test_all_unit --gtest_output="xml:report.xml"
    - mkdir coverage
    - lcov --capture --directory CMakeFiles/test_all_unit.dir/ --output-file coverage/coverage.info
    - genhtml coverage/coverage.info --output-directory coverage
  artifacts:
    paths:
      - $CI_PROJECT_DIR/build/test/coverage
      - $CI_PROJECT_DIR/build/test/test_all_unit
    reports:
      junit: $CI_PROJECT_DIR/build/test/report.xml
