# This file is a template, and might need editing before it works on your project.
# use the official gcc image, based on debian
# can use verions as well, like gcc:5.2
# see https://hub.docker.com/_/gcc/

stages:
  - build
  - test

build:alltests:
  tags:
  - raspberrypi
  
  stage: build
  script:
    - mkdir build
    - cd build
    - cmake -DCMAKE_BUILD_TYPE=Debug ..
    - cmake --build . --target test_all_unit
  artifacts:
    paths:
    - $CI_PROJECT_DIR/build/test/test_all_unit
    - $CI_PROJECT_DIR/build/test/CMakeFiles/test_all_unit.dir/__/src

test:alltests:
  tags:
  - raspberrypi
  
  stage: test
  script:
    - cd build/test
    - sudo ./test_all_unit --gtest_output="xml:report.xml"
    - mkdir -p coverage
    - lcov --capture --directory CMakeFiles/test_all_unit.dir/__/src --output-file coverage/coverage.info
    - genhtml coverage/coverage.info --output-directory coverage
  dependencies: 
    - build:alltests
  artifacts:
    paths:
      - $CI_PROJECT_DIR/build/test/coverage
    reports:
      junit: $CI_PROJECT_DIR/build/test/report.xml
  after_script:
    - sudo chown -R gitlab-runner:gitlab-runner $CI_PROJECT_DIR/build
